### ISSUE TITLE
install.sh fails after downloading asdf

### ISSUE THREAD

**Issue by maximvl** [luismbo/cl-travis#13]
Hi, I just tried to add my project to travis, yml looks correct, though install.sh fails.

travis.yml: https://github.com/maximvl/lbot/blob/master/.travis.yml
travis build log: https://travis-ci.org/maximvl/lbot/jobs/64073643#L305
error message: ```Unable to determine RC file for ''.```

**Comment by luismbo** [comment]
The install.sh script is seeing an empty $LISP variable for some reason. The only difference I see between your script and others that work is that you call `sudo`. I don't know why that would break things, but can you try removing that?

**Comment by luismbo** [comment]
Yeah, some playing around with sudo locally suggests that it doesn't inherit environment variables. So, that should be it. :-) Hope that helped.

**Comment by maximvl** [comment]
@luismbo but without sudo it fails too =(
https://travis-ci.org/maximvl/lbot/jobs/64082940#L99

**Comment by luismbo** [comment]
Oh, add 'sudo: required' to your .travis.yml. I'll update the instructions to mention this.
