### ISSUE TITLE
Allegro CL license issue

### ISSUE THREAD

**Issue by neil-lindquist** [luismbo/cl-travis#21]
The Allegro tests for fiveam started failing with the message "Lisp has expired. See http://www.franz.com/support/newlicense."  
I haven't had a chance to look that deep into it yet, but my first few tests didn't get anything working
First failure:  https://travis-ci.org/neil-lindquist/fiveam/jobs/317496321
Previous run, on the same commit: https://travis-ci.org/neil-lindquist/fiveam/jobs/317134187

**Comment by luismbo** [comment]
Thanks for the report. Not sure why the cron cl-travis builds didn't pick
this up. It might be a matter of upgrading to ACL 10.1. I'll try that ASAP.

**Comment by luismbo** [comment]
Ah, https://github.com/luismbo/cl-travis/issues/16 is why.

**Comment by neil-lindquist** [comment]
Does this issue related to CIM being deprecated?  http://keens.github.io/blog/2017/01/29/deprecating_cim/

**Comment by luismbo** [comment]
I suppose it is related, yes. cl-travis is using CIM to install Allegro CL, and we won't be using CIM to install a more recent version. The best way to fix this might be to install ACL ourselves, without CIM. Do you want to take a stab at that?

**Comment by neil-lindquist** [comment]
Sure
